---
# tasks file for httpd
  - name: Install apache webserver
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - "{{ package }}"

  - name: start the service if it is not started
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - "{{ package }}"

  - name: copy the index.html into webserver
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/

  - name: changing the port number
    ansible.builtin.template:
      src: httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
    notify: Restart httpd
